name: Nodepool Table Output

on:
  workflow_dispatch:

jobs:
  report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install pyyaml

      - name: Run Python Script
        run: python generate_table.py